load data
  infile 'data.csv'
  into table DATOS_DG_MEDICION
  fields terminated by ","
  (CLASIFICACION,FECHA DATE "dd/mm/yy",ASIGNACION,REGION_FISCAL,CAMPO_OFICIAL,NOMBRE_POZO,API,S_PERC,C1_PERC,C2_PERC,C3_PERC,C4_PERC,IC4_PERC,C5_PLUS_PERC,CO2_PERC,H2S_PERC,N2_PERC,C5_PLUS_BTU_FT3,PETROLEO_MBD,AGUA_MBD,GAS_ASOC_MMPCD,GAS_NASOC_MMPCD,GAS_MMPCD,CONDENSADO_MBD,RGA_MMPCD_MBD,TIPO_PETROLEO,API_ASIG,S_PERC_ASIG,C1_PERC_ASIG,C2_PERC_ASIG,C3_PERC_ASIG,C4_PERC_ASIG,IC4_PERC_ASIG,C5_PLUS_ASIG,CO2_PERC_ASIG,H2S_PERC_ASIG,N2_PERC_ASIG,C1_ASIG_BTU_PC,C2_ASIG_BTU_PC,C3_ASIG_BTU_PC,C4_ASIG_BTU_PC,C5_ASIG_BTU_PC,C5_PLUS_ASIG_BTU_PC,ASIG_BTU_PC,ASIG_MMBTU,C5_PLUS_ASGI_100_BTU_PC,VOL_C5_PLUS_ASIG_MMPCD,BPCE_ASIG_MBD,DIAS_MES,BPCE_MES_ASIG_MBLS,DIAS_PRODUCCION)
