load data
  infile 'DATOS_LICITACIONES_campos.csv'
  into table DATOS_LICITACIONES_CAMPOS
  fields terminated by ',' optionally enclosed by '"'
  TRAILING NULLCOLS
  (ID_BLOQUE,CAMPO,VOL_ORIGINAL,VOL_ORIGINAL_ACEITE,VOL_ORIGINAL_GAS,RESERVAS_1P,RESERVAS_2P,RESERVAS_3P,CRUDO_1P,CRUDO_2P,CRUDO_3P,GAS_1P,GAS_2P,GAS_3P)
