load data
  infile 'OFERTAS_BLOQUES.csv'
  into table LICITACIONES_BLOQUES_OFERTAS
  fields terminated by ',' optionally enclosed by '"'
  (RONDA,LICITACION,VAR_ADJ1,VAR_ADJ2,VPO,BONO,ID_LICITANTE,ID_BLOQUE,ID_EMPRESA,ID_LICITANTE_ADJ,EMPRESA,PAIS,INV_USD,AREA,VALIDEZ,LICITANTE,CONTRATO)
