load data
  infile 'BLOQUES_OFERTAS.csv'
  into table LICITACIONES_BLOQUES_OFERTAS1
  fields terminated by ',' optionally enclosed by '"'
  TRAILING NULLCOLS
  (RONDA,LICITACION,VAR_ADJ1,VAR_ADJ2,VPO,BONO,ID_LICITANTE,ID_BLOQUE,ID_EMPRESA,ID_LICITANTE_ADJ,EMPRESA,PAIS,INV_USD,AREA,VALIDEZ,LICITANTE,CONTRATO,POZOS_COMPROMETIDOS)
