load data
  infile 'RONDAS_ofertas.csv'
  into table DATOS_LICITACIONES_OFERTAS
  fields terminated by ","
  TRAILING NULLCOLS
  (ID_LICITANTE,ID_RONDA,RONDA,LIC,BLOQUE,NUM,CONTRATO,VAR_ADJ1,VAR_ADJ2,VPO,BONO,ID_OPERADOR,GANADOR,SEGUNDO_LUGAR,ID_ADJ,ADJ)
